plugins:
  katex:
    enable: true
    inject: |
      <link rel="stylesheet" href="https://gcore.jsdelivr.net/npm/katex@0.16/dist/katex.min.css">
  callout:
    enable: true
    inject: |
      <link rel="stylesheet" href="/css/callout.css">

logo:
  avatar: '[{config.avatar}](/social/)'

footer:
  content: |
    本站由 [{author.name}](/) 使用 [{theme.name} {theme.version}]({theme.tree}) 主题创建。
    本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
    全站访问量 <span id="busuanzi_site_pv">-</span> 次 · 访客数 <span id="busuanzi_site_uv">-</span> 人 · 本页面浏览 <span id="busuanzi_page_pv">-</span> 次
    <script src="//cdn.busuanzi.cc/busuanzi/3.6.9/busuanzi.min.js" defer></script>

# # 侧边栏主功能导航菜单
menubar:
  columns: 4
  items:
    - id: post
      theme: '#1BCDFC'
      icon: solar:documents-bold-duotone
      title: 博客
      url: /
    - id: social
      theme: '#FF8F2C'
      icon: solar:planet-bold-duotone
      title: 社交
      url: /social/

# # 侧边栏主功能导航菜单
# menubar:
#   columns: 4
#   items:
#     - id: post
#       theme: '#1BCDFC'
#       icon: solar:documents-bold-duotone
#       title: 博客
#       url: /
#     - id: about
#       theme: '#FF8F2C'
#       icon: solar:user-bold-duotone
#       title: 关于
#       url: /about/
